name: delora
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbd8a1cb_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.10.17=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=79.0.1=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.6
      - aiosignal==1.3.1
      - async-timeout==5.0.1
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - datasets==2.18.0
      - dill==0.3.8
      - docstring-parser==0.16
      - evaluate==0.4.3
      - filelock==3.16.1
      - fire==0.7.0
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - future==1.0.0
      - grpcio==1.68.0
      - gurobipy==12.0.0
      - huggingface-hub==0.26.2
      - idna==3.10
      - imageio==2.36.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - pyarrow==18.0.0
      - pyarrow-hotfix==0.6
      - pygments==2.18.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentencepiece==0.2.0
      - shtab==1.7.1
      - six==1.16.0
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tokenizers==0.15.2
      - torch==2.5.1
      - tqdm==4.67.0
      - transformers==4.39.1
      - triton==3.1.0
      - trl==0.10.1
      - typing-extensions==4.12.2
      - tyro==0.9.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.17.2
